### ISSUE TITLE
Master matrix job is not processing

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1154]
see http://machydra.brq.redhat.com:8080/view/RedDeer/job/RedDeer_master_matrix/

**Comment by mmalina** [comment]
It seems there is a problem with rewok. It runs RHEL 7 and for some reason webpages are open in Firefox instead of the internal browser in Eclipse. But dummy job works fine there.
Let's try firebird instead. I removed rewok from stable-linux and put firebird there instead. Also, I changed the RedDeer matrix job accordingly.
