### ISSUE TITLE
org.jboss.reddeer.workbench.test.editor.EditorTest.isNotActiveTest default

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1164]
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix/jdk=sunjdk1.7,label=firebird/643/testReport/junit/org.jboss.reddeer.workbench.test.editor/EditorTest/isNotActiveTest_default/?

Stacktrace

java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.jboss.reddeer.workbench.test.editor.EditorTest.isNotActiveTest(EditorTest.java:216)

**Comment by ljelinkova** [comment]
I looked at the failed test but since there is no screenshot archived for this run I am not able to say what caused the problem. My guess is some lost focus or 2 editors open (instead of one) but without screenshot these are just guesses. 

If you find some other run with this test failing, please add link.

**Comment by jpeterka** [comment]
Job was aborted so there are no screenshots. I have no other job with this issue. I'll move this to 1.0 and if it does't occur again I think we can close it then.

**Comment by ljelinkova** [comment]
I think this issue is not occurring any more- closing the issue.
