### ISSUE TITLE
Add a support of multiple conditions to @RunIf 

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1362]

**Comment by scabanovich** [comment]
One of possible solutions is to return array in RunIf.conditionClass(). That will not require to change existing annotations because both @RunIf(conditionClass=A.class) and @RunIf(conditionClass={A.class}) are legal. Returning an array implies that developer may want to choose if all conditions should pass, or at least one. So, annotation may be this:

public @interface RunIf {

	public enum Operation {
		AND,
		OR;
	}

	/**
	 * Condition class.
	 *
	 * @return the class<? extends test method should run>
	 */
	Class<? extends TestMethodShouldRun>[] conditionClass();

	/**
	 * In case of several condition classes, if AND operation is selected then all conditions should pass,
	 * if OR operation is selected then at least one condition should pass.
	 * Defaults to AND
	 *  
	 * @return either Operation.AND or Operation.OR, defaults to Operation.AND
	 */
	Operation operation() default Operation.AND;
}

To use it in RequirementsRunner, this helper will decide if child framework method should run:

	/**
	 * Returns true if operation is AND and all condition classes return true in shouldRun(child).
	 * Returns true if operation is OR and at least one of condition classes returns true in shouldRun(child).
	 * Otherwise, returns false.
	 * 
	 * @param runIfAnnotation
	 * @param child
	 * @return
	 * @throws IllegalAccessException if one of condition classes is not accessible
	 * @throws InstantiationException if one of condition classes cannot be instantiated
	 */
	private boolean shouldRun(RunIf runIfAnnotation, FrameworkMethod child) throws IllegalAccessException, InstantiationException {
		boolean isAnd = RunIf.Operation.AND.equals(runIfAnnotation.operation());
		for (Class<? extends TestMethodShouldRun> coditionClass: runIfAnnotation.conditionClass()) {
			boolean b = coditionClass.newInstance().shouldRun(child);
			if(isAnd != b) {
				return b;
			}
		}
		return isAnd;
	}

It will be used in isIgnored(FrameworkMethod) with this replacement

-                               if (runIfAnnotation.conditionClass().newInstance().shouldRun(child)) {
+                               if (shouldRun(runIfAnnotation, child)) {

@mlabuda , please consider this solution. If something does not fit into the idea of the issue, please let me know.
