### ISSUE TITLE
ConsoleView.clearConsole() should handle case, when Clear cnsole button is not there

### ISSUE THREAD

**Issue by rhopp** [jboss-reddeer/reddeer#1473]
When no console is opened (no build or something else has been run), the Clear console button is not there. I believe clearConsole should handle this situation instead of handling it further down the way (like so: https://github.com/jbosstools/jbosstools-integration-tests/blob/9d56b57f6429de4f211d86ba797307835f77c457/tests/org.jboss.tools.docker.ui.bot.test/src/org/jboss/tools/docker/ui/bot/test/image/PullImageTest.java#L61)

**Comment by mlabuda** [comment]
I think there should be used check whether there is something to clear, not hiding logic to clearConsole method which should have various behavior. Because then we would also have to manage disabled tool item to clear console, not only not present. And we do not handle such logic mostly. Test you are referencing should use following
`if (consoleView.consoleHasLaunch() && !consoleView.getConsoleText().isEmpty()) {
	consoleView.clearConsole();
}`

**Comment by rawagner** [comment]
dup of https://github.com/jboss-reddeer/reddeer/issues/1437
