### ISSUE TITLE
Migrate Javadoc job

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#1608]

**Comment by mmalina** [comment]
@mlabuda first, as discussed offline, javadoc in the code is currently broken in many places and you're working on it. So that's a prerequisite.
And second, "migrate javadoc job" where? Can you provide more details on what you'd like to achieve?
Migrate to central ci perhaps? For reference, this is the old job:
http://machydra.brq.redhat.com:8080/job/RedDeer_master_javadoc/

**Comment by mlabuda** [comment]
I've created a PR to fix javadoc issues #1607. Once this is merged, build will pass. I modified javadoc building - it will build javadoc only for plugins, not tests anymore. Once this is done, it would be good to migrate job to Central CI.

**Comment by mmalina** [comment]
ok, great.
For more reference, this is the original issue where we added the javadoc job: https://github.com/jboss-reddeer/reddeer/pull/46

**Comment by mmalina** [comment]
#1607 is merged and I checked the jenkins job on machydra and it seems to be blue again. Also, http://javadoc-reddeer.rhcloud.com shows RedDeer 2.0, so hopefully it's up to date now.
So I will move this job to central ci.

**Comment by mmalina** [comment]
Moved to Central CI and working as expected:
https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/RedDeer/job/reddeer.javadoc/
