### ISSUE TITLE
Complete tests of swt widgets

### ISSUE THREAD

**Issue by ljelinkova** [jboss-reddeer/reddeer#794]
Every swt widget should have at least one test in swt.test plugin. The following is (incomplete) list of widgets without tests:

DefaultList

**Comment by mlabuda** [comment]
Another missing tests:
* Label
* Menu tests (ToolbarMenu and ShellMenu)
* Shell test (DefaultShell and WorkbenchShell)
* Toolbar tests (DefaultToolBar, ViewToolBar, ViewToolItem)

**Comment by jrichter1** [comment]
So, what exactly is there to test? I looked through the existing tests and all of the tests listed as missing are present in the o.j.r.swt.test package, just not each in a separate class.

These test classes are present:
LabelTest class for labels
MenuTest class for the menus
ShellTest class for the shells
ToolBarTest class for the toolbars

Is there something I'm missing, or this issue is no longer relevant?

**Comment by ljelinkova** [comment]
If tests are already present, please move them to the appropriate packages and rename them to correspond to the tested class name (e.g rename ShellTest to WorkbenchShellTest). 

The aim is to be able to find the tests for every widget easily - by the package and the name of the widget.
