### ISSUE TITLE
jpeterka_Create documentation on How to extend Project class

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#920]

**Comment by mlabuda** [comment]
https://github.com/jboss-reddeer/reddeer/wiki/Extension-of-Project

**Comment by rawagner** [comment]
Article shouldnt be in UI section of user guide.

**Comment by mlabuda** [comment]
Moved to Eclipse section on the main page of user guide.

**Comment by vpakan** [comment]
Please make it more rich use links and code style where appropriate. It should be called Custom Project and it is not just about adding new project. Should be more descriptive about purpose of creating Custom project e.g. Java Project, Maven project. Would be nice to have some real example described.

Steps needed to create custom project should not be displayed as ordered list because order is not important in this case

**Comment by mlabuda** [comment]
https://github.com/jboss-reddeer/reddeer/wiki/Custom-Project

**Comment by jpeterka** [comment]
reviewed
