### ISSUE TITLE
ProblemsView improvements?

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#977]
Hi guys (@mlabuda, @vpakan, @ljelinkova ,@rawagner,@apodhrad), referring #962

This used construction (ehm, at least widely used by me)
```java
problemsView.getAllErrors();
```
is now deprecated

and instead of that nice call l I have to use
```java
problemsView.getProblems(ProblemsView.ProblemType.ERROR)
```
Do you really think it's an improvement?

Compare this usage;
```java
assertTrue("No errors after import are expected", pv.getAllErrors().size() == 0);
```
vs
```java
assertTrue("No errors after import are expected", pv.getProblems(ProblemsView.ProblemType.ERROR).size() == 0);
```

Am I the only one who think that the old API was better?

**Comment by jpeterka** [comment]
Ok, I can at least simplify it to this 
```java
assertTrue("No errors after import are expected", pv.getProblems(ProblemType.ERROR).size() == 0);
```
Still not as good as before but acceptable

**Comment by vpakan** [comment]
New API is much more flexible and it always comes with a price. You can always create assertNoErrors() method and you will have it even more simple than with old API.

Old API would not work when columns in ProblemsView will be reordered for example.

**Comment by mlabuda** [comment]
pv.getProblems(ProblemType.ERROR).isEmpty() looks fine. We, me and Vlado, discussed this for a long time because there were issues with preserving compatilibity and using same method name - getProblems, getErrors. Because deprecated methods use fixed amount of matchers (5) and new method would use various amount of matchers, then in case of using a new method with precisely 5 matchers it would call the deprecated one and it would not work. So we decided to create more general and easy to use method getProblems.

**Comment by jpeterka** [comment]
Ok guys, I will still miss that method but that's my pain. However thank you for clarification and hints. I'll close this one. Maybe in next version when deprecated methods will be gone I'll try to add them again compatible with new API :).
